### PR TITLE
36 correct balance calculation

### PR DESCRIPTION
**Pull request by mischanvp**
Hello,
can someone review who has time and wants to look on product code again. @pmayd @YannLadner @tvolegtv 
Description of all and dummy data in the corresponding issue #36
 
What I did:
- added a test for checking that the calculation of the balance makes sense
- removed the loop for year >= 2021 in that function and removed year entirely from that function because it lead to wrong calculations for 2021 product balance (check out the issue) / I did not add any code only removed

### CODE REVIEW

**Comment by pmayd** [comment]
Will do later!  But you have conflicts with the target branch so please also merge develop again, pls :)

**Comment by mischanvp** [comment]
> Will do later! But you have conflicts with the target branch so please also merge develop again, pls :)

Merci. How does this work? It's not the same as rebase?

**Comment by pmayd** [comment]
> > Will do later! But you have conflicts with the target branch so please also merge develop again, pls :)
> 
> Merci. How does this work? It's not the same as rebase?

What do you mean? If you want to do a rebase you can rebase instead, but I explained several times that rebase is much more complicated and I would advice against it unless you know what you do. With rebase you apply all commits again on top of develop and have to solve conflicts several times instead of having a single merge with the current state of your branch. But you can try out both strategies as you can always abort, for example `git merge --abort`. So my comment was not meant to tell you which method to use but more about that you did not have the latest changes of develop on your current branch ;) That is why GitHub is telling you "This branch has conflicts"

**Comment by mischanvp** [comment]
> > > Will do later! But you have conflicts with the target branch so please also merge develop again, pls :)
> > 
> > 
> > Merci. How does this work? It's not the same as rebase?
> 
> What do you mean? If you want to do a rebase you can rebase instead, but I explained several times that rebase is much more complicated and I would advice against it unless you know what you do. With rebase you apply all commits again on top of develop and have to solve conflicts several times instead of having a single merge with the current state of your branch. But you can try out both strategies as you can always abort, for example `git merge --abort`. So my comment was not meant to tell you which method to use but more about that you did not have the latest changes of develop on your current branch ;) That is why GitHub is telling you "This branch has conflicts"

Oki my question was intending to put more emphasis on the "How does this work?", because I never did a merge. But I think I figured it out? If I did it correctly it's indeed simpler than rebase.

**Comment by tvolegtv** [comment]
Hi, 
I have errors if I try to run the run_a4d_product_data.R for real data. For example, 
For 03_2021 AN Clinic_YA A4D Tracker.xlsx: 
_Error in compute_balance(product_df, year) : unused argument (year)
In addition: Warning messages:
1: In rm(CurrSheet) : object 'CurrSheet' not found
2: In rm(df_final) : object 'df_final' not found
3: In rm(df_out) : object 'df_out' not found
4: In rm(product_df) : object 'product_df' not found
5: All formats failed to parse. No formats found._

For 02_2020 AN Clinic_YA A4D Tracker.xlsx:
_Error in compute_balance(product_df, year) : unused argument (year)
In addition: Warning messages:
1: In rm(CurrSheet) : object 'CurrSheet' not found
2: In rm(df_final) : object 'df_final' not found
3: In rm(df_out) : object 'df_out' not found
4: In rm(product_df) : object 'product_df' not found
5: All formats failed to parse. No formats found. 
6: There was 1 warning in `mutate()`.
ℹ In argument: `product_units_received = ifelse(index %in% drop_rows, 0, as.numeric(product_units_received))`.
Caused by warning in `ifelse()`:
! NAs introduced by coercion_

Do you have the same?

**Comment by pmayd** [comment]
> > > > Will do later! But you have conflicts with the target branch so please also merge develop again, pls :)
> > > 
> > > 
> > > Merci. How does this work? It's not the same as rebase?
> > 
> > 
> > What do you mean? If you want to do a rebase you can rebase instead, but I explained several times that rebase is much more complicated and I would advice against it unless you know what you do. With rebase you apply all commits again on top of develop and have to solve conflicts several times instead of having a single merge with the current state of your branch. But you can try out both strategies as you can always abort, for example `git merge --abort`. So my comment was not meant to tell you which method to use but more about that you did not have the latest changes of develop on your current branch ;) That is why GitHub is telling you "This branch has conflicts"
> 
> Oki my question was intending to put more emphasis on the "How does this work?", because I never did a merge. But I think I figured it out? If I did it correctly it's indeed simpler than rebase.

oh sorry but yes, seems this way haha. 
To merge you do the following steps:
1. `git switch develop`
2. `git pull`
3. `git switch <your-branch>`
4. `git merge develop`
5. fix any conflicts
6. `git commit`
7. `git push`

**Comment by mischanvp** [comment]
> Hi, I have errors if I try to run the run_a4d_product_data.R for real data. For example, For 03_2021 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found._
> 
> For 02_2020 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found. 6: There was 1 warning in `mutate()`. ℹ In argument: `product_units_received = ifelse(index %in% drop_rows, 0, as.numeric(product_units_received))`. Caused by warning in `ifelse()`: ! NAs introduced by coercion_
> 
> Do you have the same?

Ups yes how did I miss that. One sec I need to remove the year

**Comment by mischanvp** [comment]
> > Hi, I have errors if I try to run the run_a4d_product_data.R for real data. For example, For 03_2021 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found._
> > For 02_2020 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found. 6: There was 1 warning in `mutate()`. ℹ In argument: `product_units_received = ifelse(index %in% drop_rows, 0, as.numeric(product_units_received))`. Caused by warning in `ifelse()`: ! NAs introduced by coercion_
> > Do you have the same?
> 
> Ups yes how did I miss that. One sec I need to remove the year

Sorry @tvolegtv  can you check again. :D I just removed the year parameter from that function.

**Comment by tvolegtv** [comment]
> > Hi, I have errors if I try to run the run_a4d_product_data.R for real data. For example, For 03_2021 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found._
> > For 02_2020 AN Clinic_YA A4D Tracker.xlsx: _Error in compute_balance(product_df, year) : unused argument (year) In addition: Warning messages: 1: In rm(CurrSheet) : object 'CurrSheet' not found 2: In rm(df_final) : object 'df_final' not found 3: In rm(df_out) : object 'df_out' not found 4: In rm(product_df) : object 'product_df' not found 5: All formats failed to parse. No formats found. 6: There was 1 warning in `mutate()`. ℹ In argument: `product_units_received = ifelse(index %in% drop_rows, 0, as.numeric(product_units_received))`. Caused by warning in `ifelse()`: ! NAs introduced by coercion_
> > Do you have the same?
> 
> Ups yes how did I miss that. One sec I need to remove the year

Thanks! It seems it runs OK.
I will check the products’ output more carefully during the weekend.

**Comment by tvolegtv** [comment]
Hi,
With these changes:
All product results for data 2017-2020 are identical to the outputs of the previous code.

For data 2021:
- 03_2021:
 product_balance - fixed
product_hospital - fixed
product_country – not fixed (but the tracker 03_2021 doesn’t contain country info in the correct place)
- 05_2021:
product_balance – not fixed
product_hospital - fixed 
product_country - fixed

**Comment by mischanvp** [comment]
> Hi, With these changes: All product results for data 2017-2020 are identical to the outputs of the previous code.
> 
> For data 2021:
> 
> * 03_2021:
>   product_balance - fixed
>   product_hospital - fixed
>   product_country – not fixed (but the tracker 03_2021 doesn’t contain country info in the correct place)
> * 05_2021:
>   product_balance – not fixed
>   product_hospital - fixed
>   product_country - fixed

Thank you Oleg. Exactly the code change did not touch 2017-2020 product data. 
Where do you see the product_balance not fixed for 05_2021 data?

**Comment by tvolegtv** [comment]
Mischan, please see the example for 05_2021 in the picture attached. 
In the tracker, Accu-Chek Performa Glucometer Set ends with 1, but after R script it ends with 2. Can you duplicate that? 

But you are right, it is a new issue. It wasn’t in the same way before the changes. And maybe it is a question to Tyla also, because here it could be a mistake in the tracker with the start or with 26.02.2021 status.

Because there are 2 possible calculations here: 
-	Start with 1, received 2, released 2, and end with 1
-	Or start with 2, received 2, released 2, and end with 2
But the tracker looks like: start with 2 (26.02.2021), received 2, released 2, and end with 1

**Comment by mischanvp** [comment]
> Mischan, please see the example for 05_2021 in the picture attached. In the tracker, Accu-Chek Performa Glucometer Set ends with 1, but after R script it ends with 2. Can you duplicate that?
> 
> But you are right, it is a new issue. It wasn’t in the same way before the changes. And maybe it is a question to Tyla also, because here it could be a mistake in the tracker with the start or with 26.02.2021 status.
> 
> Because there are 2 possible calculations here:
> 
> * Start with 1, received 2, released 2, and end with 1
> * Or start with 2, received 2, released 2, and end with 2
>   But the tracker looks like: start with 2 (26.02.2021), received 2, released 2, and end with 1
>   

Ah thank you. Oki understood.
So the function for product_balance calculation is correct itself, but the problem comes from earlier where they order each product by date from line 130. That's why **26-02-2021** becomes the starting date instead of **28-02-2021**. Because if 28-02-2021 remains the starting date it would still be 1+2-2.

_# Extend product name and sort by product
    product_df <- product_df %>% ungroup() %>% tidyr::fill(c(product, product_entry_date), .direction = "down") %>%
      arrange(., product, product_entry_date)_

So should we maybe code in a way that the first date remains untouched and the remaining dates are ordered? Or what do you think?
And yes would be also a good question for Tyla with the dates. I thought maybe it's typos.

**Comment by tvolegtv** [comment]
Yes, the product_balance calculation is correct. It is a question about what rules we should consider more reliable for each product - “start date” or “date”.
It looks like we should consider start dates more reliable, as you wrote – _“we maybe code in a way that the first date remains untouched and the remaining dates are ordered”_

But, maybe, it is better to confirm with Tyla.

**Comment by mischanvp** [comment]
> Yes, the product_balance calculation is correct. It is a question about what rules we should consider more reliable for each product - “start date” or “date”. It looks like we should consider start dates more reliable, as you wrote – _“we maybe code in a way that the first date remains untouched and the remaining dates are ordered”_
> 
> But, maybe, it is better to confirm with Tyla.

yes agree

**Comment by tvolegtv** [comment]
As a result of our discussion about the balance question – “the balance should be stable”. It seems that Mischan’s idea should be implemented just with a small remark  – _“So should we maybe code in a way that the first **(and last)** date remains untouched and the remaining dates are ordered?”_

**Comment by mischanvp** [comment]
> As a result of our discussion about the balance question – “the balance should be stable”. It seems that Mischan’s idea should be implemented just with a small remark – _“So should we maybe code in a way that the first **(and last)** date remains untouched and the remaining dates are ordered?”_

Oki thank you. I will correct it then accordingly and let you know to review.

**Comment by mischanvp** [comment]
@tvolegtv  Can you please check again whether it matches now when you have time? I only looked at some examples in 2021 and 2020 data. Now should look like this:
Bildschirmfoto 2023-05-12 um 22 32 02

**Comment by tvolegtv** [comment]
Thanks! I checked all trackers (8 xlsx files), and all of them, except 02_2020, with changes. Sometimes these changes are very significant.
It seems that everything is correct now.

**Pull request merged**
