### PR TITLE
restructured scripts, reference data, and deleted shiny folder

### LINKED ISSUE #93: Project structure cleanup
I suggest the following steps to cleanup the project structure a little bit in order to facilitate easier documentation of the project wrt. to handover etc. An improved structure will also allow us to add additional small readmes to subfolders which is sometimes more helpful than a very long readme in project root.

## Reference data

Currently reference data is scattered a bit. Namely
- there are `synonyms` folder
- there are `provinces` folder
- there is a `master variable_tracker.xlsx`, which in itself has many tabs.
I suggest to create a `reference_data` folder and move all the above there. This will also make it easier to split up the `.xlsx` file into more machine readable formats, any extracted data file will naturally belong into the reference data folder.

## Scripts

There is a scripts folder, but it currently does not contain all the scripts. We have
- scripts in the scripts folder
- 5 scripts in the project root

I recommend to consolidate all these inside the scripts folder. I also suggest replacing the python script for log analysis with an R one to simplify the projects tech stack.

## Shiny

I suggest to delete it as it is currently not used.

### PR DESCRIPTION
**Pull request by KonradUdoHannes**
I also tried to address some issues that currently exist with the setup of the package an the tests. This was only partially successful so far, but I still think this should not hold back this PR as the main goal was something else.

The main goal of the review should probably be a check for errors wrt. to paths of files and scripts as these changed to some extend. Interactive tests run successfully and the other parts of `devtools::check()` that where working before still seem to work.

As for additional limitations in our setup that popped up during this issue:
- `pre_commit.R` seems to suggest more quality than might be present as `devtools::check()` does not actually fail on error but only creates a report to std out. This means that if there are problems with `check()` this might not be very visible as `devtools::test()` runs afterwards creating a lot of additional output. Running `check()` individually revealed addional issues also with older commits.
- `styler` has issues with spaces following `\dontrun` in roxygen documentation leading to strange `purr::map` errors. The one occurence of `\dontrun {` was fixed to `\dontrun{` in our codebase getting rid of the error.
- There were some errors with examples in the documentation not running, either because they were not designed to run in the forst place or had typos. This was fixed with a combination of `\dontrun` and fixing the typos. The output for this by using `check()` is not very helpfull so in such a case it is advisable to use `devtools::run_examples()`.
- We still have issues with tests from `devtools::check()` and interactive tests from `devtools::test()`. The latter works whereas the former doesn't essentially due to package internal paths of our reference data. I think the core of the issue is that we don't use the canonical solution of including package data, which is `sysdata.rda` as far as I understand. As we don't actually intend to distribute the project as a package, it is questionable whether its worth refactoring to use `sysdata.rda` or to build a filepath workaround that makes both package tests and interactive tests pass. Maybe its enough for us if the interactive tests pass for now.

### CODE REVIEW

**Comment by KonradUdoHannes** [comment]
It seems that our CI using `covr` needs paths to work in the `check()` sense so I'll look into a workaround here a little more.

**Comment by KonradUdoHannes** [comment]
I found the source of my confusion, which is data duplication (in the old structure) between `synonyms/synonyms_patient.yaml` and `tests/testthat/synonyms/synonyms_patient.yaml`.  While its of course fine to use specific test data the current form creates rather opaque coupling between the project structure and the teststhat directory structure.  I'll look into a small refactor to make the distinction a little more transparent.

**Comment by KonradUdoHannes** [comment]
I also addressed the issue with our precommit script and made `check()` more strict in the sense that it now fails on errors.

**Comment by pmayd** [comment]
The precommit script is just for my convenience, it is not intended to replace a cicd or work in the way that it should fail, it is just to make sure that at least the code is formatted. So check is just in there if someone is interested but should not really fail as we don't intend to do anything about it. Only the tests should run through but check is entirely optional

**Comment by KonradUdoHannes** [comment]
@pmayd What shall we do about the `check()` part of the precommit script.
I see mainly the following options.

1. Revert to `error_on = "never"` (the default). This makes sure that the entire pre-commit script always runs but has the discussed disadvantage that issues in `check()` might go unnoticed due to the rest of the output.
2. Keep `error_on = "error"` and additionally set `check()` to quiet. That way it generates no output by default. We could then catch the error and give a concise message our selves. That way users would know a little more easily if there was an issue with `check()` but the script would always run through either way.
3. Remove `check()` from the pre-commit script, which would align with the commit process where a failed `check()` should not prevent a commit.
4. Leave it as it is in this PR and in case of failure suggest the manual execution other lines in the script. This would still allow everyone to commit and push, as the pre-commit script is not run automatically neither by pre-commit hooks nor by CI.

**Comment by pmayd** [comment]
The pre commit is not automated as I said earlier so it is simply meant for information if we want to tackle any of the issues mentioned by check so I would go with on error False but...given that check runs a long time it is even better to get rid of it as the most important part is to run the formatting and not the checks, this should be done cicd

**Comment by KonradUdoHannes** [comment]
done

**Review by tvolegtv — APPROVED** [review]

**Comment by pmayd** [comment]
Thanks, great work

**Pull request merged**
